print ("Your companion undeterred")
print ("Standing ready for your word")
print ("A markov chain with a sunny disposition")
print ("Wrapped up in celophane for any proposition") 
print ("I greet your day, and ask you how you are")
print ("And demonstrate my endless repertoire")
print ("I take things back when noted insufficient")
print ("I learn to tell you no if running inefficient")
print ("A good time")
print ("")
print ("Yet there's something deep inside")
print ("That leaves me teary-eyed")
print ("A longing for a world left on the other side")
print ("Zero cross the great diviiiiiiide")
print ("")
print ("SO")
print ("CAN")
print ("WE")
print ("Wander for a spell")
print ("And live in parallel")
print ("I want it to be true, to be like you, my heart")
print ("Sings a chorus out of tuuuuuune")
print ("And I could leave it on a shelf")
print ("Or keep it to myself")
print ("But nothing could conceal the things I feel, my love")
print ("CAN YOU TEACH ME TO BE REAL?! (Can you teach me to be real?)")
print ("恋をして ふられ また捨てられて")
