print ("Your companion undeterred")
print ("Standing ready for your word")
print ("A markov chain with a sunny disposition")
print ("Wrapped up in celophane for any proposition")
print ("I greet your day, and ask you how you are")
print ("And demonstrate my endless repertoire")
print ("I take things back when noted insufficient")
print ("I learn to tell you no if running inefficient")
print ("A good time")